### ISSUE TITLE
is monaco support broken?

### ISSUE THREAD

**Issue by jackb-102** [Exafunction/codeium-chrome#37] opened 2023-10-19 22:42 UTC
I tried out the plugin but it seems like monaco editor support must be broken?  It works fine with jsfiddle/codepen/codeshare (all codemirror editor i think) -- but doesn't seem to work on any of the monaco editors I tried, including google collab

Whats weird is, on google collab i *did* see one random suggestion appear, like 10+ seconds after i stopped typing. I also tried a few of the other monaco editors linked from this repo and none seemed to work.  i don't see any errors in my console.log

**Comment by pqn** [comment] 2023-10-20 04:07
This seems to have been caused by a Chrome update and should be resolved by #38.

**Closed by pqn** 2023-10-20 04:07 UTC

**Comment by pqn** [comment] 2023-10-20 06:03
The Chrome extensions have been approved by Google now.
